### ISSUE TITLE
snapshout-remount-fs fails on args with double =

### ISSUE THREAD

**Issue by aburmash** [snapshotmanager/boom#25]
in function def _arg_in_cmdline(cmdline, arg):
[systemd/snapshot-remount-fs](https://github.com/snapshotmanager/boom/blob/main/systemd/snapshot-remount-fs#L52C1-L62C17)
if there a cmdline argument with double = ( for example `rd.iscsi.param=node.session.timeo.replacement_timeout=6000`)
`(word, _) = word.split("=")
`will fail.
instead
`word = word.split("=")[0] `seem to be a better universal choice to get word value.

**Comment by bmr-cymru** [comment]
I've pushed a fix for this and another bug that I noticed while reviewing the script. These will both be in the next release, 1.6.1.
